// megafunction wizard: %ALTCLKCTRL%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altclkctrl 

// ============================================================
// File Name: wm_xclk_mux.v
// Megafunction Name(s):
// 			altclkctrl
//
// Simulation Library Files(s):
// 			cycloneii
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 10.0 Build 218 06/27/2010 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2010 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altclkctrl CBX_AUTO_BLACKBOX="ALL" CLOCK_TYPE="Global Clock" DEVICE_FAMILY="Cyclone II" ENA_REGISTER_MODE="falling edge" USE_GLITCH_FREE_SWITCH_OVER_IMPLEMENTATION="ON" clkselect ena inclk outclk
//VERSION_BEGIN 10.0 cbx_altclkbuf 2010:06:27:21:21:57:SJ cbx_cycloneii 2010:06:27:21:21:57:SJ cbx_lpm_add_sub 2010:06:27:21:21:57:SJ cbx_lpm_compare 2010:06:27:21:21:57:SJ cbx_lpm_decode 2010:06:27:21:21:57:SJ cbx_lpm_mux 2010:06:27:21:21:57:SJ cbx_mgl 2010:06:27:21:25:48:SJ cbx_stratix 2010:06:27:21:21:57:SJ cbx_stratixii 2010:06:27:21:21:57:SJ cbx_stratixiii 2010:06:27:21:21:57:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = clkctrl 1 reg 3 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  wm_xclk_mux_altclkctrl_nbi
	( 
	clkselect,
	ena,
	inclk,
	outclk) /* synthesis synthesis_clearbox=2 */;
	input   [1:0]  clkselect;
	input   ena;
	input   [3:0]  inclk;
	output   outclk;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  clkselect;
	tri1   ena;
	tri0   [3:0]  inclk;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	ena_reg;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	[1:0]	select_reg;
	wire  wire_clkctrl1_outclk;
	wire  [1:0]  clkselect_wire;
	wire  [3:0]  inclk_wire;
	wire  [1:0]  select_enable_wire;

	// synopsys translate_off
	initial
		ena_reg = {1{1'b1}};
	// synopsys translate_on
	always @ ( negedge wire_clkctrl1_outclk)
		  ena_reg <= (ena & (~ select_enable_wire[1]));
	// synopsys translate_off
	initial
		select_reg = 0;
	// synopsys translate_on
	always @ ( negedge wire_clkctrl1_outclk)
		if (ena_reg == 1'b0)   select_reg <= clkselect_wire[1:0];
	cycloneii_clkctrl   clkctrl1
	( 
	.clkselect({select_reg}),
	.ena(1'b1),
	.inclk(inclk_wire),
	.outclk(wire_clkctrl1_outclk)
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		clkctrl1.clock_type = "Global Clock",
		clkctrl1.lpm_type = "cycloneii_clkctrl";
	assign
		clkselect_wire = {clkselect},
		inclk_wire = {inclk},
		outclk = (wire_clkctrl1_outclk & ena_reg),
		select_enable_wire = {(select_enable_wire[0] | (clkselect_wire[1] ^ select_reg[1])), (clkselect_wire[0] ^ select_reg[0])};
endmodule //wm_xclk_mux_altclkctrl_nbi
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module wm_xclk_mux (
	clkselect,
	ena,
	inclk0x,
	inclk1x,
	inclk2x,
	inclk3x,
	outclk)/* synthesis synthesis_clearbox = 2 */;

	input	[1:0]  clkselect;
	input	  ena;
	input	  inclk0x;
	input	  inclk1x;
	input	  inclk2x;
	input	  inclk3x;
	output	  outclk;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	[1:0]  clkselect;
	tri1	  ena;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  sub_wire0;
	wire  sub_wire5 = inclk3x;
	wire  sub_wire4 = inclk2x;
	wire  sub_wire3 = inclk1x;
	wire  outclk = sub_wire0;
	wire  sub_wire1 = inclk0x;
	wire [3:0] sub_wire2 = {sub_wire5, sub_wire4, sub_wire3, sub_wire1};

	wm_xclk_mux_altclkctrl_nbi	wm_xclk_mux_altclkctrl_nbi_component (
				.clkselect (clkselect),
				.ena (ena),
				.inclk (sub_wire2),
				.outclk (sub_wire0))/* synthesis synthesis_clearbox=2
	 clearbox_macroname = altclkctrl
	 clearbox_defparam = "ena_register_mode=falling edge;intended_device_family=Cyclone II;use_glitch_free_switch_over_implementation=ON;clock_type=Global Clock;" */;

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: PRIVATE: clock_inputs NUMERIC "4"
// Retrieval info: CONSTANT: ENA_REGISTER_MODE STRING "falling edge"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: CONSTANT: USE_GLITCH_FREE_SWITCH_OVER_IMPLEMENTATION STRING "ON"
// Retrieval info: CONSTANT: clock_type STRING "Global Clock"
// Retrieval info: USED_PORT: clkselect 0 0 2 0 INPUT GND "clkselect[1..0]"
// Retrieval info: USED_PORT: ena 0 0 0 0 INPUT VCC "ena"
// Retrieval info: USED_PORT: inclk0x 0 0 0 0 INPUT NODEFVAL "inclk0x"
// Retrieval info: USED_PORT: inclk1x 0 0 0 0 INPUT NODEFVAL "inclk1x"
// Retrieval info: USED_PORT: inclk2x 0 0 0 0 INPUT NODEFVAL "inclk2x"
// Retrieval info: USED_PORT: inclk3x 0 0 0 0 INPUT NODEFVAL "inclk3x"
// Retrieval info: USED_PORT: outclk 0 0 0 0 OUTPUT NODEFVAL "outclk"
// Retrieval info: CONNECT: @clkselect 0 0 2 0 clkselect 0 0 2 0
// Retrieval info: CONNECT: @ena 0 0 0 0 ena 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 0 inclk0x 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 1 inclk1x 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 2 inclk2x 0 0 0 0
// Retrieval info: CONNECT: @inclk 0 0 1 3 inclk3x 0 0 0 0
// Retrieval info: CONNECT: outclk 0 0 0 0 @outclk 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL wm_xclk_mux.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL wm_xclk_mux.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL wm_xclk_mux.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL wm_xclk_mux.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL wm_xclk_mux_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL wm_xclk_mux_bb.v FALSE
// Retrieval info: LIB_FILE: cycloneii
