/* MTI_DPI */

/*
 * Copyright 2002-2010 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32pe'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


DPI_LINK_DECL DPI_DLLESPEC
double
syn_cos(
    double rTheta);

DPI_LINK_DECL DPI_DLLESPEC
double
syn_log(
    double rVal);

DPI_LINK_DECL DPI_DLLESPEC
double
syn_log10(
    double rVal);

DPI_LINK_DECL DPI_DLLESPEC
double
syn_sin(
    double rTheta);

#endif 
